// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  center: string
  container: string
  drawerContainer: string
  errorMessageScreen: string
  filler: string
  icon: string
  iconClickable: string
  loadingDots: string
  mainContainer: string
  noteEditorContainer: string
  noteListContainer: string
  overlay: string
  sideBarContainer: string
  tagModalContainer: string
}
declare var cssExports: CssExports
export = cssExports
