// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  filler: string
  icon: string
  iconClickable: string
}
declare var cssExports: CssExports
export = cssExports
