// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string
  date: string
  filler: string
  header: string
  icon: string
  iconClickable: string
  placeholder: string
  preview: string
  tag: string
  tagList: string
  title: string
}
declare var cssExports: CssExports
export = cssExports
