// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string
  contentContainer: string
  contentInput: string
  dateDesc: string
  datesContainer: string
  emptyMessage: string
  filler: string
  header: string
  icon: string
  iconClickable: string
  tagListContainer: string
  titleContainer: string
  titleInput: string
}
declare var cssExports: CssExports
export = cssExports
