// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  clickableRow: string
  container: string
  editButton: string
  empty: string
  filler: string
  icon: string
  iconClickable: string
  noteCount: string
  row: string
  sidebarIcon: string
  tagName: string
  tagRow: string
  tagRowZero: string
}
declare var cssExports: CssExports
export = cssExports
