// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string
  doneButton: string
  filler: string
  icon: string
  iconClickable: string
  iconSmall: string
  input: string
  inputContainer: string
  row: string
  shadowInput: string
  tagName: string
}
declare var cssExports: CssExports
export = cssExports
