// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  chip: string
  chipContent: string
  container: string
  filler: string
  icon: string
  iconClickable: string
  input: string
  inputContainer: string
  lastRow: string
  lastRowSelected: string
  removeButton: string
  row: string
  rowSelected: string
  selectedChip: string
  shadowInput: string
  suggestionBox: string
}
declare var cssExports: CssExports
export = cssExports
